version: "3.8"

networks:
  confectionary-nets:
    external: true

# Storage outside the containers
volumes:
  data-orderer.confectionary.com:
  data-shop1.confectionary.com:
  data-shop2.confectionary.com:
  data-mill.flourmill.com:
  data-ovens.bakingstuff.com:

services:
  development:
    hostname: devweb
    build:
      context: .
      dockerfile: Dockerfile.Dev
    command: |
      sleep infinity
    stop_grace_period: 5s
    volumes:
      - ../..:/workspaces:cached
    networks:
      - confectionary-nets

  # Orderer service
  orderer.confectionary.com:
    container_name: orderer.confectionary.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=ERROR
    volumes:
      - ${PWD}/config/orderer:/var/hyperledger/config
      - ${PWD}/config/crypto-config/ordererOrganizations/confectionary.com/orderers/orderer.confectionary.com/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/ordererOrganizations/confectionary.com/orderers/orderer.confectionary.com/tls:/var/hyperledger/tls
      - data-orderer.confectionary.com:/var/ledger
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - confectionary-nets

  shop1.confectionary.com:
    container_name: shop1.confectionary.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=confectionary-nets
    command: peer node start
    volumes:
      - ${PWD}/config/shop1:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/confectionary.com/peers/shop1/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/confectionary.com/peers/shop1/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-shop1.confectionary.com:/var/hyperledger/production
    depends_on:
      - orderer.confectionary.com
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      - confectionary-nets

  shop2.confectionary.com:
    container_name: shop2.confectionary.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=confectionary-nets
    command: peer node start
    volumes:
      - ${PWD}/config/shop2:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/confectionary.com/peers/shop2/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/confectionary.com/peers/shop2/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-shop2.confectionary.com:/var/hyperledger/production
    depends_on:
      - orderer.confectionary.com
    ports:
      - 8051:7051
      - 8052:7052
    networks:
      - confectionary-nets

  mill.flourmill.com:
    container_name: mill.flourmill.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=confectionary-nets
    command: peer node start
    volumes:
      - ${PWD}/config/mills:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/flourmill.com/peers/mill/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/flourmill.com/peers/mill/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-mill.flourmill.com:/var/hyperledger/production
    depends_on:
      - orderer.confectionary.com
    ports:
      - 9051:7051
      - 9052:7052
    networks:
      - confectionary-nets

  ovens.bakingstuff.com:
    container_name: ovens.bakingstuff.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=confectionary-nets
    command: peer node start
    volumes:
      - ${PWD}/config/ovens:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/bakingstuff/peers/ovens/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/bakingstuff/peers/ovens/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-ovens.bakingstuff.com:/var/hyperledger/production
    depends_on:
      - orderer.confectionary.com
    ports:
      - 10051:7051
      - 10052:7052
    networks:
      - confectionary-nets
