version: "3.8"

networks:
  dmarket-nets:
    external: true

# Storage outside the containers
volumes:
  data-orderer.dmarket.com:
  data-buyer.dmarket.com:
  data-seller.dmarket.com:
  data-bank.dmarket.com:

services:
  development:
    hostname: devweb
    build:
      context: .
      dockerfile: Dockerfile.Dev
    command: |
      sleep infinity
    stop_grace_period: 5s
    volumes:
      - ../..:/workspaces:cached
    networks:
      - dmarket-nets

  # Orderer service
  orderer.dmarket.com:
    container_name: orderer.dmarket.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=ERROR
    volumes:
      - ${PWD}/config/orderer:/var/hyperledger/config
      - ${PWD}/config/crypto-config/ordererOrganizations/dmarket.com/orderers/orderer.dmarket.com/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/ordererOrganizations/dmarket.com/orderers/orderer.dmarket.com/tls:/var/hyperledger/tls
      - data-orderer.dmarket.com:/var/ledger
    ports:
      - 7050:7050
      - 8443:8443
    networks:
      - dmarket-nets

  buyer.dmarket.com:
    container_name: buyer.dmarket.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=BuyerMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dmarket-nets
    command: peer node start
    volumes:
      - ${PWD}/config/buyer:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/buyer.dmarket.com/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/buyer.dmarket.com/peers/buyer/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-buyer.dmarket.com:/var/hyperledger/production
    depends_on:
      - orderer.dmarket.com
    ports:
      - 7051:7051
      - 7052:7052
    networks:
      - dmarket-nets

  seller.dmarket.com:
    container_name: seller.dmarket.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=SellerMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dmarket-nets
    command: peer node start
    volumes:
      - ${PWD}/config/seller:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/dmarket.com/peers/seller/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/dmarket.com/peers/seller/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-seller.dmarket.com:/var/hyperledger/production
    depends_on:
      - orderer.dmarket.com
    ports:
      - 8051:7051
      - 8052:7052
    networks:
      - dmarket-nets

  bank.dmarket.com:
    container_name: bank.dmarket.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dmarket-nets
    command: peer node start
    volumes:
      - ${PWD}/config/bank:/var/hyperledger/config
      - ${PWD}/config/crypto-config/peerOrganizations/dmarket.com/peers/bank/msp:/var/hyperledger/msp
      - ${PWD}/config/crypto-config/peerOrganizations/dmarket.com/peers/bank/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-bank.dmarket.com:/var/hyperledger/production
    depends_on:
      - orderer.dmarket.com
    ports:
      - 9051:7051
      - 9052:7052
    networks:
      - dmarket-nets
