# Capabilities
Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

# Organizations
Organizations:
  - &Buyer
    Name: Buyer
    ID: BuyerMSP
    MSPDir: ./crypto-config/peerOrganizations/buyer.dmarket.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BuyerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('BuyerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('BuyerMSP.admin')"
    AnchorPeers:
      - Host: buyer.dmarket.com
        Port: 7051

  - &Seller
    Name: Seller
    ID: SellerMSP
    MSPDir: ./crypto-config/peerOrganizations/seller.dmarket.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SellerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('SellerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('SellerMSP.admin')"
    AnchorPeers:
      - Host: seller.dmarket.com
        Port: 8051

  - &Bank
    Name: Bank
    ID: BankMSP
    MSPDir: ./crypto-config/peerOrganizations/bank.dmarket.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BankMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('BankMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('BankMSP.admin')"
    AnchorPeers:
      - Host: bank.dmarket.com
        Port: 9051

  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/dmarket.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

# Orderer
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.dmarket.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

# Application
Application: &ApplicationDefaults
  ACLs: &ACLsDefault
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetConfigTree: /Channel/Application/Readers
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Readers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
  Policies: &ApplicationDefaultPolicies
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
  Organizations:
  Capabilities:
    <<: *ApplicationCapabilities

# Channel
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# Profiles
Profiles:
  DMarketOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - <<: *Orderer
    Consortiums:
      DMarketConsortium:
        Organizations:
          - <<: *Buyer
          - <<: *Seller
          - <<: *Bank
  DMarketChannel:
    <<: *ChannelDefaults
    Consortium: DMarketConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - <<: *Buyer
        - <<: *Seller
        - <<: *Bank
