OrdererOrgs:
  - Name: Orderer
    Domain: dmarket.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Buyer
    Domain: buyer.dmarket.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Seller
    Domain: seller.dmarket.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Bank
    Domain: bank.dmarket.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
