################################################################################
#
#   Orderer Configuration
#
################################################################################
General:
  BootstrapMethod: file
  BootstrapFile: /var/hyperledger/config/confectionary-genesis.block

  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        Keystore:

  LocalMSPDir: /var/hyperledger/msp
  LocalMSPID: OrdererMSP

  ListenAddress: 0.0.0.0
  ListenPort: 7050

  Cluster:
    SendBufferSize: 10
    ClientCertificate:
    ClientPrivateKey:
    ListenPort:
    ListenAddress:
    ServerCertificate:
    ServerPrivateKey:

  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s

  TLS:
    Enabled: false
    PrivateKey: ./server.key
    Certificate: ./server.crt
    RootCAs:
      - ./ca.crt
    ClientAuthRequired: false
    ClientRootCAs:

################################################################################
#
#   SECTION: File Ledger
#
################################################################################
FileLedger:
  Location: /var/ledger
  Prefix: hyperledger-fabric-ordererledger

################################################################################
#
#   Debug Configuration
#
################################################################################
Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

################################################################################
#
#   Operations Configuration
#
################################################################################
Operations:
  ListenAddress: 127.0.0.1:8443

  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    RootCAs: []

################################################################################
#
#   Metrics Configuration
#
################################################################################
Metrics:
  Provider: disabled

  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix:

################################################################################
#
#   Consensus Configuration (etcdraft)
#
################################################################################
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
